version: "3"
services:
  db:
    container_name: mydb
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    container_name: myapp
    links: 
      - "db"
    build: ./
    ports:
      - "5000:5000"